export type DemoCoverageStatus =
  | "runtime-demo"
  | "docs-only"
  | "test-only"
  | "edge-case"
  | "missing";

export interface DemoCoverageEntry {
  name: string;
  kind: "component" | "widget" | "hook" | "subsystem";
  status: DemoCoverageStatus;
  location: string;
  note: string;
}

export const DEMO_COVERAGE: readonly DemoCoverageEntry[] = [
  { name: "Accordion", kind: "component", status: "runtime-demo", location: "Effects", note: "Compact disclosure sample." },
  { name: "Alert", kind: "component", status: "runtime-demo", location: "Overlays", note: "Inline warning banner." },
  { name: "AnimatePresence", kind: "component", status: "runtime-demo", location: "Effects", note: "Dynamic list mount/unmount." },
  { name: "ApprovalPrompt", kind: "widget", status: "runtime-demo", location: "AI", note: "Tool approval flow." },
  { name: "AreaChart", kind: "component", status: "runtime-demo", location: "Charts", note: "Filled load series." },
  { name: "Avatar", kind: "component", status: "test-only", location: "components.test.ts", note: "Visual primitive covered by focused tests." },
  { name: "Badge", kind: "component", status: "runtime-demo", location: "Welcome / Themes", note: "Status pills." },
  { name: "BarChart", kind: "component", status: "runtime-demo", location: "Charts", note: "Task duration bars." },
  { name: "BlinkDot", kind: "widget", status: "runtime-demo", location: "Welcome / Anim Lab", note: "Streaming indicator." },
  { name: "Box", kind: "component", status: "runtime-demo", location: "All sections", note: "Primary layout primitive." },
  { name: "Breadcrumb", kind: "component", status: "runtime-demo", location: "Overlays", note: "Navigation strip sample." },
  { name: "Button", kind: "component", status: "runtime-demo", location: "Forms / Calendar", note: "Primary action controls." },
  { name: "Calendar", kind: "component", status: "runtime-demo", location: "Calendar", note: "Date-grid picker." },
  { name: "Canvas", kind: "component", status: "runtime-demo", location: "Effects", note: "Node/edge canvas." },
  { name: "Card", kind: "component", status: "test-only", location: "components.test.ts", note: "Generic frame covered by rendering tests." },
  { name: "ChatInput", kind: "component", status: "runtime-demo", location: "Forms", note: "Composer control." },
  { name: "Checkbox", kind: "component", status: "runtime-demo", location: "Forms", note: "Boolean input." },
  { name: "Collapsible", kind: "component", status: "runtime-demo", location: "Effects", note: "Single-panel disclosure." },
  { name: "CommandBlock", kind: "widget", status: "runtime-demo", location: "AI", note: "Runnable command block." },
  { name: "CommandDropdown", kind: "widget", status: "runtime-demo", location: "AI", note: "Slash-command picker." },
  { name: "CommandPalette", kind: "component", status: "runtime-demo", location: "Overlays", note: "Controlled command launcher." },
  { name: "ConfirmDialog", kind: "component", status: "runtime-demo", location: "Overlays", note: "Visible confirm dialog sample." },
  { name: "ContentSwitcher", kind: "component", status: "docs-only", location: "docs/features.md", note: "Covered by transition demos; direct sample deferred." },
  { name: "ContextWindow", kind: "widget", status: "runtime-demo", location: "AI", note: "Token budget bar." },
  { name: "CostTracker", kind: "widget", status: "runtime-demo", location: "AI", note: "Spend readout." },
  { name: "DataGrid", kind: "component", status: "runtime-demo", location: "Data", note: "Sortable editable data model." },
  { name: "DatePicker", kind: "component", status: "runtime-demo", location: "Calendar", note: "Bounded date chooser." },
  { name: "DefinitionList", kind: "component", status: "runtime-demo", location: "About / Calendar", note: "Term-definition content." },
  { name: "Diagram", kind: "component", status: "runtime-demo", location: "Effects", note: "Node graph." },
  { name: "DiffView", kind: "component", status: "runtime-demo", location: "Editor", note: "Unified/split diff." },
  { name: "Digits", kind: "component", status: "runtime-demo", location: "Effects", note: "Large numeric display." },
  { name: "DirectoryTree", kind: "component", status: "runtime-demo", location: "Data", note: "Filesystem tree with custom loader." },
  { name: "Divider", kind: "component", status: "runtime-demo", location: "Shell / Calendar", note: "Section separator." },
  { name: "Editor", kind: "component", status: "runtime-demo", location: "Editor", note: "Code editor." },
  { name: "ErrorBoundary", kind: "component", status: "test-only", location: "robustness.test.ts", note: "Failure boundary belongs in tests." },
  { name: "EventCalendar", kind: "component", status: "runtime-demo", location: "Calendar", note: "Scheduling views." },
  { name: "FilePicker", kind: "component", status: "runtime-demo", location: "Data", note: "Static file picker tree." },
  { name: "FocusGroup", kind: "component", status: "edge-case", location: "Overlays internals", note: "Used internally by focus-trapped overlays." },
  { name: "Footer", kind: "component", status: "docs-only", location: "docs/features.md", note: "Shell uses custom footer chrome." },
  { name: "Form", kind: "component", status: "runtime-demo", location: "Forms", note: "Schema-driven mini form." },
  { name: "Gauge", kind: "component", status: "runtime-demo", location: "Charts", note: "CPU/memory gauges." },
  { name: "GlowText", kind: "component", status: "runtime-demo", location: "Effects", note: "Animated glow text." },
  { name: "Gradient", kind: "component", status: "runtime-demo", location: "Effects", note: "Gradient title." },
  { name: "GradientBorder", kind: "component", status: "runtime-demo", location: "Effects", note: "Multi-color border." },
  { name: "GradientProgress", kind: "component", status: "runtime-demo", location: "Effects", note: "Animated progress bar." },
  { name: "Header", kind: "component", status: "docs-only", location: "docs/features.md", note: "Demo shell has bespoke header." },
  { name: "Heading", kind: "component", status: "runtime-demo", location: "About", note: "Section heading sample." },
  { name: "Heatmap", kind: "component", status: "runtime-demo", location: "Charts", note: "2D matrix chart." },
  { name: "HelpPanel", kind: "component", status: "runtime-demo", location: "Overlays", note: "Inline shortcut panel." },
  { name: "Histogram", kind: "component", status: "runtime-demo", location: "Charts", note: "Frequency chart." },
  { name: "Image", kind: "component", status: "edge-case", location: "docs/features.md", note: "Terminal graphics protocol support is capability-dependent." },
  { name: "InlineDiff", kind: "component", status: "runtime-demo", location: "Editor", note: "Word-level diff." },
  { name: "Kbd", kind: "component", status: "runtime-demo", location: "All interactive sections", note: "Keyboard hints." },
  { name: "KeyboardHelp", kind: "component", status: "runtime-demo", location: "Shell", note: "Global help modal." },
  { name: "LineChart", kind: "component", status: "runtime-demo", location: "Charts", note: "Multi-series chart." },
  { name: "Link", kind: "component", status: "runtime-demo", location: "Effects", note: "OSC-8 hyperlink sample." },
  { name: "ListView", kind: "component", status: "runtime-demo", location: "Layout", note: "Selectable list." },
  { name: "LoadingIndicator", kind: "component", status: "runtime-demo", location: "Overlays", note: "Determinate loading card." },
  { name: "Markdown", kind: "component", status: "runtime-demo", location: "Editor", note: "Inline markdown rendering." },
  { name: "MarkdownEditor", kind: "component", status: "runtime-demo", location: "Editor", note: "Editor plus live preview." },
  { name: "MarkdownViewer", kind: "component", status: "runtime-demo", location: "Editor", note: "Scrollable markdown document." },
  { name: "MaskedInput", kind: "component", status: "runtime-demo", location: "Forms", note: "Phone/date style input." },
  { name: "Menu", kind: "component", status: "runtime-demo", location: "Overlays", note: "Command menu." },
  { name: "MessageBubble", kind: "widget", status: "runtime-demo", location: "AI", note: "Chat message display." },
  { name: "Modal", kind: "component", status: "runtime-demo", location: "Shell", note: "Global help overlay." },
  { name: "ModelBadge", kind: "widget", status: "runtime-demo", location: "Welcome / AI", note: "Model identity chip." },
  { name: "Newline", kind: "component", status: "test-only", location: "components.test.ts", note: "Text-flow primitive covered by tests." },
  { name: "OperationTree", kind: "widget", status: "runtime-demo", location: "AI", note: "Operation hierarchy." },
  { name: "OptionList", kind: "component", status: "docs-only", location: "docs/features.md", note: "Select/ListView demos cover the interaction model." },
  { name: "OrderedList", kind: "component", status: "runtime-demo", location: "About", note: "Numbered content." },
  { name: "Overlay", kind: "component", status: "runtime-demo", location: "Overlays", note: "Movable/resizable panels." },
  { name: "OverlayProvider", kind: "component", status: "runtime-demo", location: "Overlays", note: "Overlay manager provider." },
  { name: "Paginator", kind: "component", status: "runtime-demo", location: "Overlays", note: "Page selector." },
  { name: "Pane", kind: "component", status: "docs-only", location: "docs/features.md", note: "Panes child slot; layout section covers split behavior separately." },
  { name: "Panes", kind: "component", status: "docs-only", location: "docs/features.md", note: "Split-pane sample still planned." },
  { name: "Paragraph", kind: "component", status: "test-only", location: "components.test.ts", note: "Text wrapping covered by tests." },
  { name: "PerformanceHUD", kind: "widget", status: "runtime-demo", location: "AI", note: "Dev HUD metrics panel." },
  { name: "Placeholder", kind: "component", status: "docs-only", location: "docs/features.md", note: "Empty-state primitive not expanded in demo." },
  { name: "Pretty", kind: "component", status: "runtime-demo", location: "Data", note: "JSON-like value display." },
  { name: "ProgressBar", kind: "component", status: "runtime-demo", location: "Themes", note: "Theme preview progress." },
  { name: "RadioGroup", kind: "component", status: "runtime-demo", location: "Forms", note: "Exclusive choice." },
  { name: "RevealTransition", kind: "component", status: "runtime-demo", location: "Effects", note: "Reveal animation." },
  { name: "RichLog", kind: "component", status: "runtime-demo", location: "Data", note: "Structured log stream." },
  { name: "ScatterPlot", kind: "component", status: "runtime-demo", location: "Charts", note: "XY plot with trend line." },
  { name: "ScrollView", kind: "component", status: "runtime-demo", location: "Many sections", note: "Scrollable panes." },
  { name: "SearchInput", kind: "component", status: "docs-only", location: "docs/features.md", note: "SearchList and SearchTable cover search flows." },
  { name: "SearchList", kind: "component", status: "runtime-demo", location: "Search", note: "Search-and-pick list." },
  { name: "SearchTable", kind: "component", status: "runtime-demo", location: "Data", note: "Filterable table." },
  { name: "Select", kind: "component", status: "runtime-demo", location: "Forms", note: "Dropdown choice." },
  { name: "SelectInput", kind: "component", status: "test-only", location: "select.test.ts", note: "Ink-style API covered by focused tests." },
  { name: "SelectionList", kind: "component", status: "docs-only", location: "docs/features.md", note: "MultiSelect hook card covers the state model." },
  { name: "Shadow", kind: "component", status: "runtime-demo", location: "Effects", note: "Drop-shadow sample." },
  { name: "ShimmerText", kind: "widget", status: "runtime-demo", location: "Anim Lab", note: "Thinking shimmer." },
  { name: "Spacer", kind: "component", status: "runtime-demo", location: "Shell / Effects", note: "Flex spacing primitive." },
  { name: "Sparkline", kind: "component", status: "runtime-demo", location: "Charts / Hooks", note: "Tiny trend chart." },
  { name: "Spinner", kind: "component", status: "runtime-demo", location: "Welcome / Themes", note: "Animated loading glyph." },
  { name: "Static", kind: "component", status: "test-only", location: "components.test.ts", note: "Render-once primitive belongs in tests." },
  { name: "StatusLine", kind: "widget", status: "runtime-demo", location: "AI", note: "Model/token status." },
  { name: "StatusMessage", kind: "component", status: "runtime-demo", location: "Overlays", note: "Inline status text." },
  { name: "Stepper", kind: "component", status: "runtime-demo", location: "Forms", note: "Form progress." },
  { name: "Stopwatch", kind: "component", status: "runtime-demo", location: "Effects", note: "Elapsed-time readout." },
  { name: "StreamingText", kind: "widget", status: "runtime-demo", location: "AI", note: "Token stream text." },
  { name: "Switch", kind: "component", status: "runtime-demo", location: "Forms", note: "On/off input." },
  { name: "SyntaxHighlight", kind: "widget", status: "runtime-demo", location: "Editor", note: "Language-aware code." },
  { name: "TabbedContent", kind: "component", status: "runtime-demo", location: "Overlays", note: "Compact tabs with body." },
  { name: "Table", kind: "component", status: "runtime-demo", location: "Data", note: "Read-only table." },
  { name: "Tabs", kind: "component", status: "runtime-demo", location: "Overlays", note: "Tab strip." },
  { name: "Tag", kind: "component", status: "runtime-demo", location: "Forms", note: "Label chip." },
  { name: "Text", kind: "component", status: "runtime-demo", location: "All sections", note: "Core text primitive." },
  { name: "TextArea", kind: "component", status: "runtime-demo", location: "Forms", note: "Multi-line input." },
  { name: "TextInput", kind: "component", status: "runtime-demo", location: "Forms", note: "Single-line input." },
  { name: "Timer", kind: "component", status: "runtime-demo", location: "Effects", note: "Countdown readout." },
  { name: "Toast", kind: "component", status: "runtime-demo", location: "Shell", note: "Notification body." },
  { name: "ToastContainer", kind: "component", status: "runtime-demo", location: "Overlays", note: "Stacked notification manager." },
  { name: "TokenStream", kind: "widget", status: "runtime-demo", location: "AI", note: "Token rate display." },
  { name: "Tooltip", kind: "component", status: "runtime-demo", location: "Overlays", note: "Visible tooltip sample." },
  { name: "Transition", kind: "component", status: "runtime-demo", location: "Effects", note: "Slide transition." },
  { name: "Tree", kind: "component", status: "runtime-demo", location: "Data", note: "Expandable tree." },
  { name: "TreeTable", kind: "component", status: "runtime-demo", location: "Data", note: "Hierarchical table." },
  { name: "UnorderedList", kind: "component", status: "runtime-demo", location: "About", note: "Bulleted content." },
  { name: "VirtualList", kind: "component", status: "runtime-demo", location: "Data", note: "Windowed list sample." },
  { name: "Welcome", kind: "component", status: "runtime-demo", location: "Welcome", note: "Splash primitive preview." },

  { name: "useFocus", kind: "hook", status: "edge-case", location: "Hooks", note: "Focus state is visible through focus-managed components." },
  { name: "useFocusManager", kind: "hook", status: "edge-case", location: "Hooks", note: "Global manager; exercised through shell/focus tests." },
  { name: "useVirtualList", kind: "hook", status: "runtime-demo", location: "Data / Hooks", note: "VirtualList uses it and hook card lists it." },
  { name: "useCommandPalette", kind: "hook", status: "runtime-demo", location: "Overlays / Hooks", note: "CommandPalette behavior card." },
  { name: "useTimer", kind: "hook", status: "runtime-demo", location: "Effects / Hooks", note: "Timer primitive." },
  { name: "usePhaseTimer", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Timing hook card." },
  { name: "useGhostText", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Completion hook card." },
  { name: "useImperativeAnimation", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Animation loop hook card." },
  { name: "useClipboard", kind: "hook", status: "edge-case", location: "Hooks", note: "OSC-52 support is terminal-dependent." },
  { name: "usePaste", kind: "hook", status: "edge-case", location: "Hooks", note: "Bracketed paste needs terminal input." },
  { name: "useKeyChord", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Input hook card." },
  { name: "useTypeahead", kind: "hook", status: "runtime-demo", location: "Hooks", note: "List jump hook card." },
  { name: "useMultiSelect", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Selection hook card." },
  { name: "useSortable", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Table sorting card." },
  { name: "useAsyncLoader", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Async lifecycle card." },
  { name: "useBatchAction", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Batching hook card." },
  { name: "useStreamConsumer", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Async iterable hook card." },
  { name: "useHistory", kind: "hook", status: "runtime-demo", location: "Hooks", note: "History ring card." },
  { name: "useModeCycler", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Mode cycling card." },
  { name: "useNotification", kind: "hook", status: "runtime-demo", location: "Hooks", note: "Toast queue card." },
  { name: "useContextMenu", kind: "hook", status: "edge-case", location: "Hooks", note: "Right-click behavior is mouse-environment dependent." },
  { name: "useDragReorder", kind: "hook", status: "edge-case", location: "Hooks", note: "Pointer-drag behavior is covered through data widgets." },
  { name: "useInfiniteScroll", kind: "hook", status: "edge-case", location: "Hooks", note: "Requires scroll-bound pagination trigger." },
  { name: "useCopyPasteBuffer", kind: "hook", status: "edge-case", location: "Hooks", note: "Clipboard/selection integration is terminal-dependent." },
  { name: "useStyleSheet", kind: "hook", status: "runtime-demo", location: "Hooks / Internals", note: "Stylesheet feature card." },
] as const;

export const DEMO_COVERAGE_STATUSES: readonly DemoCoverageStatus[] = [
  "runtime-demo",
  "docs-only",
  "test-only",
  "edge-case",
  "missing",
];

export function getDemoCoverage(name: string): DemoCoverageEntry | undefined {
  return DEMO_COVERAGE.find((entry) => entry.name === name);
}
